os: linux
dist: xenial
language: c
compiler: gcc

before_install:
- git clone https://github.com/jakubfi/travis-utils travis-utils
- BUILD_DEP=$TRAVIS_BUILD_DIR/travis-utils/em-build-dep.sh
- $BUILD_DEP emawp
- $BUILD_DEP emelf
- $BUILD_DEP emas

script:
- make

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
