	.include cpu.inc
	.include io.inc

	uj	start

imask:	.res 0

	.org	OS_START
	.include crc.asm

start:
	lw	r1, data+1
	lw	r2, 256
	lj	crc16
halt:
	hlt	044
	ujs	halt

data:	.word	-1
	.ascii	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	.ascii	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	.ascii	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	.ascii	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
	.word	-2

; XPCT r1 : 0xE938
